export const QUERY_GET_USERS = ["USERS", "QUERY_GET_USERS"];
export const MUTATION_CREATE_USER = ["USERS", "MUTATION_CREATE_USER"];

export const QUERY_GET_NOTES = ["NOTES", "QUERY_GET_NOTES"];
export const MUTATION_DELETE_NOTE = ["NOTES", "MUTATION_DELETE_NOTE"];
export const MUTATION_CREATE_NOTE = ["NOTES", "MUTATION_CREATE_NOTE"];
export const MUTATION_EDIT_NOTE = ["NOTES", "MUTATION_EDIT_NOTE"];

export const MUTATION_USER_MANAGEMENT_BULK_UPSERT = ["USER_MANAGEMENT", "BULK_UPSERT"];
